# Generated by Django 4.1.2 on 2022-10-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='end_job_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='start_job_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='end_job_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='start_job_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
