# Generated by Django 4.1.2 on 2022-10-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerss', '0002_categoryoffer_end_job_id_categoryoffer_start_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='end_job_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='start_job_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='end_job_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='start_job_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
