# Generated by Django 4.1.2 on 2022-10-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerss', '0003_alter_categoryoffer_end_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='disabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='disabled',
            field=models.BooleanField(null=True),
        ),
    ]
