# Generated by Django 4.1.2 on 2022-10-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_game_discount_percentage'),
        ('offerss', '0004_categoryoffer_disabled_productoffer_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offer', to='products.game', verbose_name='Game'),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='offer_type',
            field=models.CharField(choices=[('Product Offer', 'Product Offer'), ('Category Offer', 'Category_Offer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_offer', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_off', to='products.game', verbose_name='Game'),
        ),
    ]
