# Generated by Django 4.1.2 on 2022-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerss', '0006_alter_categoryoffer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
