# Generated by Django 4.1.2 on 2022-10-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_game_discount_percentage'),
        ('offerss', '0007_alter_categoryoffer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='offer_type',
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offer', to='products.game', verbose_name='Game'),
        ),
    ]
