# Generated by Django 4.1.2 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_game_discount_percentage'),
        ('offerss', '0008_remove_categoryoffer_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSaleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('discount_percentage', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Expired', 'Expired')], max_length=20)),
                ('start_job_id', models.CharField(max_length=100, null=True)),
                ('end_job_id', models.CharField(max_length=100, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('type', models.CharField(choices=[('Categories', 'Categories'), ('Games', 'Games')], max_length=10)),
                ('category', models.ManyToManyField(related_name='sale_offer', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
