# Generated by Django 4.1.2 on 2022-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_game_discount_percentage'),
        ('offerss', '0009_mainsaleoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainsaleoffer',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='mainsaleoffer',
            name='games',
            field=models.ManyToManyField(related_name='sale_offer', to='products.game'),
        ),
    ]
