# Generated by Django 4.1.2 on 2022-11-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerss', '0010_rename_category_mainsaleoffer_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='disabled',
            new_name='force_disable',
        ),
        migrations.RenameField(
            model_name='mainsaleoffer',
            old_name='disabled',
            new_name='force_disable',
        ),
        migrations.RenameField(
            model_name='productoffer',
            old_name='disabled',
            new_name='force_disable',
        ),
    ]
