# Generated by Django 4.1.2 on 2022-11-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerss', '0011_rename_disabled_categoryoffer_force_disable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Expired', 'Expired'), ('Stopped', 'Stopped')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mainsaleoffer',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Expired', 'Expired'), ('Stopped', 'Stopped')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Expired', 'Expired'), ('Stopped', 'Stopped')], max_length=20),
        ),
    ]
