version: '3.8'

services:
  monkeygamestore:
    build:
      context: .
    command: bash -c "supervisord -c /etc/supervisor/supervisord.conf && ln -s /etc/supervisor/supervisord.conf /etc/supervisord.conf && gunicorn MonkeyGameStore.wsgi --bind 0.0.0.0:8013 --workers 2"
    # command: python manage.py runserver
    # command: gunicorn MonkeyGameStore.wsgi --bind 0.0.0.0:8013 --workers 2
     # command: python manage.py runserver
    volumes:
      - .:/monkeygamestore
    image: monkeygamestore:1.0
    container_name: monkey_game_store_container
    env_file:
      - ./.env
    ports:
      - "8013:8013"
    depends_on:
      - redis_service

  nginx:
    image: nginx:latest
    ports:
      - "443:8081"
    volumes:
      - ./nginx/nginx-setup-prod.conf:/etc/nginx/conf.d/default.conf
      - ./static:/home/static:ro
      - ./media:/home/media:ro
      - ./cloudflare:/etc/ssl:ro
    depends_on:
      - monkeygamestore
  
  redis_service:
    image: redis:7.0.5-alpine
    volumes:
      - ./redis-backup:/data
    ports:
      - "6379:6379"
