# Generated by Django 4.1.2 on 2022-10-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='name',
            new_name='coupon_code',
        ),
    ]
