# Generated by Django 4.1.2 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_name_coupon_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='end_job_id',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='force_disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_job_id',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Specific Order', 'Specific Order'), ('Default', 'Default')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Expired', 'Expired')], max_length=20),
        ),
    ]
