# Generated by Django 4.1.2 on 2022-11-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_end_job_id_coupon_force_disable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(help_text='aaaaaaaaaaaaaaaaaaaaaa', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Specific Order', 'Specific Order')], max_length=20),
        ),
    ]
