# Generated by Django 4.1.2 on 2022-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_coupon_code_alter_coupon_coupon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Specific Order', 'Specific Order')], help_text='Select specific order if you want to tie this to a particular order.', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='order_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
