# Generated by Django 4.1.2 on 2022-11-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_alter_coupon_coupon_code_alter_coupon_coupon_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
