# Generated by Django 4.1.2 on 2022-11-03 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_coupon_discount_amount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent_value',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.PositiveIntegerField(default=10, verbose_name='Maximum Discount Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.PositiveIntegerField(default=10, verbose_name='Minimum Purchase Amount'),
            preserve_default=False,
        ),
    ]
