# Generated by Django 4.1.2 on 2022-11-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_alter_coupon_max_usage_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_usage_per_user_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit Per User'),
        ),
    ]
