# Generated by Django 4.1.2 on 2022-11-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_alter_coupon_valid_from_alter_coupon_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupon', to='coupons.coupon', verbose_name='Coupon'),
        ),
    ]
