# Generated by Django 4.1.2 on 2022-11-04 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0012_alter_usercoupon_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupon', to='coupons.coupon', verbose_name='Coupon'),
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together={('coupon', 'user')},
        ),
    ]
