# Generated by Django 4.1.2 on 2022-11-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0013_alter_usercoupon_coupon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together=set(),
        ),
    ]
