# Generated by Django 4.1.2 on 2022-11-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0015_usercoupon_unique coupon for user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Discount Amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
