# Generated by Django 4.1.2 on 2022-11-08 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0016_alter_coupon_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
