# Generated by Django 4.1.2 on 2022-11-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0017_coupon_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_job_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_job_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
