# Generated by Django 4.1.2 on 2022-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0018_alter_coupon_end_job_id_alter_coupon_start_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='order_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
