# Generated by Django 4.1.1 on 2022-09-17 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with this phone number already exists'}, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.ProhibitNullCharactersValidator]),
        ),
    ]
