# Generated by Django 4.1.1 on 2022-09-19 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with this phone number already exists'}, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator(regex='^[0-9]+$')]),
        ),
    ]
