# Generated by Django 4.1.1 on 2022-10-03 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useraddress_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^[0-9]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='Landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
