# Generated by Django 4.1.1 on 2022-10-07 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_useraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator(code='invalid_pin_code', message='Enter a valid pincode', regex='^[0-9]+$')], verbose_name='PINCODE'),
        ),
    ]
