# Generated by Django 4.1.2 on 2022-11-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_useraddress_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
