# Generated by Django 4.1.1 on 2022-10-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_game_salecount'),
        ('cart', '0010_alter_cart_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='products.game', verbose_name='Game'),
        ),
    ]
