# Generated by Django 4.1.1 on 2022-10-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
