# Generated by Django 4.1.2 on 2022-11-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
