# Generated by Django 4.1.2 on 2022-11-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_cart_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon',
            new_name='user_coupon',
        ),
    ]
