# Generated by Django 4.1.2 on 2022-11-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_rename_coupon_cart_user_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_coupon',
            new_name='coupon',
        ),
    ]
