# Generated by Django 4.1.1 on 2022-10-03 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^[0-9]+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^[0-9]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='Landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
