# Generated by Django 4.1.1 on 2022-10-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_billingaddress_phone_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_title',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pre_save', 'pre_save'), ('Pending Payment', 'Pending Payment'), ('Payment failed', 'Payment failed'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
