# Generated by Django 4.1.1 on 2022-10-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('presave', 'presave'), ('Pending Payment', 'Pending Payment'), ('Payment failed', 'Payment failed'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
