# Generated by Django 4.1.1 on 2022-10-10 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_game_salecount'),
        ('orders', '0009_alter_billingaddress_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.game', verbose_name='Game'),
        ),
    ]
