# Generated by Django 4.1.1 on 2022-10-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_game_salecount'),
        ('orders', '0010_alter_orderitem_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.game', verbose_name='Game'),
        ),
    ]
