# Generated by Django 4.1.1 on 2022-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='test title', max_length=100),
            preserve_default=False,
        ),
    ]
