# Generated by Django 4.1.1 on 2022-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_thumbnail',
            field=models.ImageField(null=True, upload_to='orderthumbnail/'),
        ),
    ]
