# Generated by Django 4.1.1 on 2022-10-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail/'),
        ),
    ]
