# Generated by Django 4.1.2 on 2022-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Offer Discount'),
        ),
    ]
