# Generated by Django 4.1.2 on 2022-10-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_item_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='offer_discount',
            new_name='offer_discounted_price',
        ),
    ]
