# Generated by Django 4.1.2 on 2022-10-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_rename_offer_discounted_price_orderitem_item_offer_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_discount_percentage',
            new_name='item_offer_discount_percentage',
        ),
    ]
