# Generated by Django 4.1.2 on 2022-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_rename_item_offer_discounted_price_orderitem_item_offer_discount_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_offer_discount_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_offer_discount_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
