# Generated by Django 4.1.2 on 2022-10-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderitem_item_offer_discount_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_offer_discount_percentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
