# Generated by Django 4.1.2 on 2022-10-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_orderitem_item_offer_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Paypal', 'Paypal')], max_length=20, null=True),
        ),
    ]
