# Generated by Django 4.1.2 on 2022-11-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0016_alter_coupon_max_discount_amount_and_more'),
        ('orders', '0025_order_coupon_code_order_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_orders', to='coupons.coupon'),
        ),
    ]
