# Generated by Django 4.1.2 on 2022-11-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0016_alter_coupon_max_discount_amount_and_more'),
        ('orders', '0026_order_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_orders', to='coupons.usercoupon'),
        ),
    ]
