# Generated by Django 4.1.2 on 2022-11-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_order_coupon_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_applied',
            new_name='applied_coupon',
        ),
    ]
