# Generated by Django 4.1.2 on 2022-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_rename_coupon_applied_order_applied_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='db_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
