# Generated by Django 4.1.2 on 2022-11-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_game_discount_percentage'),
        ('orders', '0029_order_db_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.game', verbose_name='Game'),
        ),
    ]
