# Generated by Django 4.1.2 on 2022-11-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('Paypal', 'Paypal'), ('Wallet', 'Wallet')], max_length=20, null=True),
        ),
    ]
