# Generated by Django 4.1.1 on 2022-09-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categoriess', to='products.category', verbose_name='Parent Category')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('base_price', models.IntegerField()),
                ('stock', models.BigIntegerField(default=1)),
                ('main_banner', models.ImageField(default=None, upload_to='mainbanner/')),
                ('thumbnail', models.ImageField(default=None, upload_to='thumbnail')),
                ('released_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('categories', models.ManyToManyField(related_name='games', to='products.category', verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='GameMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideimage', models.ImageField(default=None, upload_to='gameslideshow/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='products.game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='products.game', verbose_name='Game')),
            ],
        ),
    ]
