# Generated by Django 4.1.1 on 2022-09-23 18:35

from django.db import migrations
import image_cropping


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_banner', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_banner',
            field=image_cropping.fields.ImageCropField(default=None, upload_to='mainbanner/'),
        ),
    ]
