# Generated by Django 4.1.1 on 2022-09-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_game_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Windows', 'Windows'), ('MAC-OS', 'MAC-OS')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='game',
            name='released_on',
        ),
        migrations.RemoveField(
            model_name='game',
            name='stock',
        ),
        migrations.AddField(
            model_name='game',
            name='uploaded_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='main_banner',
            field=models.ImageField(default=None, upload_to='mainbanner/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnail/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='products.game', verbose_name='Game')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specs', to='products.platform', verbose_name='Platform')),
            ],
        ),
    ]
