# Generated by Django 4.1.1 on 2022-09-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_platform_remove_game_cropping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
