# Generated by Django 4.1.1 on 2022-10-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_game_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='salecount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
