# Generated by Django 4.1.1 on 2022-10-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_game_salecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_discountable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='max_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
