# Generated by Django 4.1.1 on 2022-10-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_category_max_quantity_game_max_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount_status',
            field=models.CharField(choices=[('None', 'None'), ('Product Discount', 'Product Discount'), ('Category Discount', 'Category Discount')], default='None', max_length=100),
        ),
    ]
