# Generated by Django 4.1.1 on 2022-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_game_discount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_discountable',
            field=models.BooleanField(default=True),
        ),
    ]
