# Generated by Django 4.1.1 on 2022-10-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_game_is_discountable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_discountable',
        ),
        migrations.AddField(
            model_name='category',
            name='discount_status',
            field=models.BooleanField(default=False),
        ),
    ]
