# Generated by Django 4.1.2 on 2022-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_category_is_discountable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
