# Generated by Django 4.1.2 on 2022-10-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_game_discount_name_game_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount_name',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
