# Generated by Django 4.1.2 on 2022-10-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_game_discount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
