# Generated by Django 4.1.2 on 2022-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_game_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount_percentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
